# Generated by Django 5.0.7 on 2024-07-24 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('patientID', models.IntegerField(primary_key=True, serialize=False)),
                ('patientName', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('history', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='USscans',
            fields=[
                ('scanID', models.AutoField(primary_key=True, serialize=False)),
                ('coordinates', models.TextField(max_length=2)),
                ('scanDate', models.DateField()),
                ('diagnosis', models.TextField(max_length=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='us_scans', to='DotPlot.patients')),
            ],
        ),
    ]
