# Generated by Django 5.0.7 on 2024-07-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DotPlot', '0002_remove_usscans_patient_patients_scanid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usscans',
            name='coordinates',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='usscans',
            name='diagnosis',
            field=models.CharField(max_length=10),
        ),
    ]
